#!/bin/bash

# ##############################################################################
# Copyright (c) 2008-2009 Andreas Bauer <baueran@gmail.com>
# ##############################################################################

if [ ! "$1" ]; then
    echo "Error: No arguments given."
    echo "The correct syntax is: ltl2mon \"<formula>\" [--prefix <directory>]"
    exit 0
fi

# Either the script is invoked from the directory where it lives in,
# or if invoked from another directory, then --prefix <DIR> can be
# used to say where ltl2mon lives in.

if [ "$2" = "--prefix" ]; then
    export PACKAGE=$3
else
    export PACKAGE=.
fi

export EXTRACT=$PACKAGE"/bin/extractalphabet"
export FSMCROSSPROD=$PACKAGE"/bin/fsmcrossprod"
export FORMTOSYM=$PACKAGE"/bin/formulatosymbols"
export NEVERTOFSM=$PACKAGE"/bin/nevertofsm"
export FSMTOOLS=$PACKAGE"/third-party"
export LTLTOBA=$PACKAGE"/third-party/ltl2ba"

export PHI=$1
export NPHI=`echo ! \( $PHI \)`
export ALPH=$($EXTRACT "$1")

$LTLTOBA -f "$PHI" > Phi.never
$NEVERTOFSM -a "$ALPH" < Phi.never > Phi.txt

$LTLTOBA -f "$NPHI" > NPhi.never
$NEVERTOFSM -a "$ALPH" < NPhi.never > NPhi.txt

$FORMTOSYM "$PHI" > actions.syms

$FSMTOOLS/fsmcompile -i actions.syms Phi.txt |\
$FSMTOOLS/fsmdeterminize |\
$FSMTOOLS/fsmminimize |\
$FSMTOOLS/fsmdraw -i actions.syms > DPhi.dot

$FSMTOOLS/fsmcompile -i actions.syms NPhi.txt |\
$FSMTOOLS/fsmdeterminize |\
$FSMTOOLS/fsmminimize |\
$FSMTOOLS/fsmdraw -i actions.syms > DNPhi.dot

$FSMCROSSPROD -m -c -a "$ALPH" -f DPhi.dot -f DNPhi.dot
rm Phi.txt NPhi.txt actions.syms DPhi.dot DNPhi.dot Phi.never NPhi.never

